package com.autumn.clever.baidu.营销的一些实体类;

import java.io.Serializable;
import java.util.Date;

/**
 * @program: sky
 * @description:
 * @author: zhangqiuying
 * @create: 2023-11-07 15:03
 **/
public class PromotionInfo implements Serializable {

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_promotion_info.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_promotion_info.promotion_id
     *
     * @mbg.generated
     */
    private Long promotionId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_promotion_info.app_id
     *
     * @mbg.generated
     */
    private Long appId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_promotion_info.uc_id
     *
     * @mbg.generated
     */
    private Long ucId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_promotion_info.shop_id
     *
     * @mbg.generated
     */
    private Long shopId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_promotion_info.promotion_type
     *
     * @mbg.generated
     */
    private Integer promotionType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_promotion_info.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_promotion_info.status
     *
     * @mbg.generated
     */
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_promotion_info.start_time
     *
     * @mbg.generated
     */
    private Date startTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_promotion_info.end_time
     *
     * @mbg.generated
     */
    private Date endTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_promotion_info.limit_condition
     *
     * @mbg.generated
     */
    private String limitCondition;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_promotion_info.discount_info
     *
     * @mbg.generated
     */
    private String discountInfo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_promotion_info.scope_type
     *
     * @mbg.generated
     */
    private Integer scopeType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_promotion_info.creater
     *
     * @mbg.generated
     */
    private Long creater;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_promotion_info.udpater
     *
     * @mbg.generated
     */
    private Long udpater;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_promotion_info.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_promotion_info.update_time
     *
     * @mbg.generated
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_promotion_info.is_delete
     *
     * @mbg.generated
     */
    private Integer isDelete;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_promotion_info.biz_type
     *
     * @mbg.generated
     */
    private Integer bizType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_promotion_info.total_stock
     *
     * @mbg.generated
     */
    private Integer totalStock;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_promotion_info.extra_info
     *
     * @mbg.generated
     */
    private String extraInfo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_promotion_info.topic
     *
     * @mbg.generated
     */
    private String topic;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_promotion_info.pay_type
     *
     * @mbg.generated
     */
    private Integer payType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_promotion_info.rel_promotion_id
     *
     * @mbg.generated
     */
    private Long relPromotionId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_promotion_info.user_limit_info
     *
     * @mbg.generated
     */
    private String userLimitInfo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_promotion_info.cashier_promotion_id
     *
     * @mbg.generated
     */
    private String cashierPromotionId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_promotion_info.budget_un_id
     *
     * @mbg.generated
     */
    private Long budgetUnId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_promotion_info.range_scope
     *
     * @mbg.generated
     */
    private String rangeScope;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_promotion_info.preheat_start_time
     *
     * @mbg.generated
     */
    private Date preheatStartTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_promotion_info.preheat_switch
     *
     * @mbg.generated
     */
    private Boolean preheatSwitch;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_promotion_info.used_num
     *
     * @mbg.generated
     */
    private Integer usedNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_promotion_info.extra_rule
     *
     * @mbg.generated
     */
    private String extraRule;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_promotion_info.activity_id
     *
     * @mbg.generated
     */
    private Long activityId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tb_promotion_info
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getPromotionId() {
        return promotionId;
    }

    public void setPromotionId(Long promotionId) {
        this.promotionId = promotionId;
    }

    public Long getAppId() {
        return appId;
    }

    public void setAppId(Long appId) {
        this.appId = appId;
    }

    public Long getUcId() {
        return ucId;
    }

    public void setUcId(Long ucId) {
        this.ucId = ucId;
    }

    public Long getShopId() {
        return shopId;
    }

    public void setShopId(Long shopId) {
        this.shopId = shopId;
    }

    public Integer getPromotionType() {
        return promotionType;
    }

    public void setPromotionType(Integer promotionType) {
        this.promotionType = promotionType;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public Integer getStatus() {
        return status;
    }

    public void setStatus(Integer status) {
        this.status = status;
    }

    public Date getStartTime() {
        return startTime;
    }

    public void setStartTime(Date startTime) {
        this.startTime = startTime;
    }

    public Date getEndTime() {
        return endTime;
    }

    public void setEndTime(Date endTime) {
        this.endTime = endTime;
    }

    public String getLimitCondition() {
        return limitCondition;
    }

    public void setLimitCondition(String limitCondition) {
        this.limitCondition = limitCondition;
    }

    public String getDiscountInfo() {
        return discountInfo;
    }

    public void setDiscountInfo(String discountInfo) {
        this.discountInfo = discountInfo;
    }

    public Integer getScopeType() {
        return scopeType;
    }

    public void setScopeType(Integer scopeType) {
        this.scopeType = scopeType;
    }

    public Long getCreater() {
        return creater;
    }

    public void setCreater(Long creater) {
        this.creater = creater;
    }

    public Long getUdpater() {
        return udpater;
    }

    public void setUdpater(Long udpater) {
        this.udpater = udpater;
    }

    public Date getCreateTime() {
        return createTime;
    }

    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    public Date getUpdateTime() {
        return updateTime;
    }

    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    public Integer getIsDelete() {
        return isDelete;
    }

    public void setIsDelete(Integer isDelete) {
        this.isDelete = isDelete;
    }

    public Integer getBizType() {
        return bizType;
    }

    public void setBizType(Integer bizType) {
        this.bizType = bizType;
    }

    public Integer getTotalStock() {
        return totalStock;
    }

    public void setTotalStock(Integer totalStock) {
        this.totalStock = totalStock;
    }

    public String getExtraInfo() {
        return extraInfo;
    }

    public void setExtraInfo(String extraInfo) {
        this.extraInfo = extraInfo;
    }

    public String getTopic() {
        return topic;
    }

    public void setTopic(String topic) {
        this.topic = topic;
    }

    public Integer getPayType() {
        return payType;
    }

    public void setPayType(Integer payType) {
        this.payType = payType;
    }

    public Long getRelPromotionId() {
        return relPromotionId;
    }

    public void setRelPromotionId(Long relPromotionId) {
        this.relPromotionId = relPromotionId;
    }

    public String getUserLimitInfo() {
        return userLimitInfo;
    }

    public void setUserLimitInfo(String userLimitInfo) {
        this.userLimitInfo = userLimitInfo;
    }

    public String getCashierPromotionId() {
        return cashierPromotionId;
    }

    public void setCashierPromotionId(String cashierPromotionId) {
        this.cashierPromotionId = cashierPromotionId;
    }

    public Long getBudgetUnId() {
        return budgetUnId;
    }

    public void setBudgetUnId(Long budgetUnId) {
        this.budgetUnId = budgetUnId;
    }

    public String getRangeScope() {
        return rangeScope;
    }

    public void setRangeScope(String rangeScope) {
        this.rangeScope = rangeScope;
    }

    public Date getPreheatStartTime() {
        return preheatStartTime;
    }

    public void setPreheatStartTime(Date preheatStartTime) {
        this.preheatStartTime = preheatStartTime;
    }

    public Boolean getPreheatSwitch() {
        return preheatSwitch;
    }

    public void setPreheatSwitch(Boolean preheatSwitch) {
        this.preheatSwitch = preheatSwitch;
    }

    public Integer getUsedNum() {
        return usedNum;
    }

    public void setUsedNum(Integer usedNum) {
        this.usedNum = usedNum;
    }

    public String getExtraRule() {
        return extraRule;
    }

    public void setExtraRule(String extraRule) {
        this.extraRule = extraRule;
    }

    public Long getActivityId() {
        return activityId;
    }

    public void setActivityId(Long activityId) {
        this.activityId = activityId;
    }
}
